baseURL = "https://lokl.dev"
languageCode = "en-us"
title = "Lokl"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2
  [[menu.main]]
    name = "Sitemap"
    url = "/sitemap/"
    weight = 3

