account_id = "69c736c51a7a73dccc0b83f75d3bedce"
name = "workers-www-lokl"
type = "webpack"
route = "lokl.dev/*"
workers_dev = false
zone_id = "df298c056754ca360fa541b55cdf3890"

[site]
bucket = "public"
entry-point = "workers-site"
