name: Deploy to Workers Prod

on:
  push:
    branches:
      - master

env:
  HUGO_VERSION: 0.83.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'true'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download Hugo
        run: sudo wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Install Hugo
        run: sudo dpkg -i hugo_${{ env.HUGO_VERSION }}_Linux-64bit.deb

      - name: Install Wrangler
        run: sudo npm install @cloudflare/wrangler -g --unsafe-perm=true --allow-root

      - name: Download HTML Tidy
        run: wget https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-64bit.deb

      - name: Install HTML Tidy
        run: sudo dpkg -i tidy-5.4.0-64bit.deb

      - name: Build
        run: export PATH=$PATH:$(pwd)/bin && hugo --gc && find public -name '*.html' -type f -print -exec tidy -mq --tidy-mark no --wrap 0 --indent auto --indent-spaces 2 --quiet yes  '{}' \;

      - name: config wrangler
        run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish
